

#curl -v -X POST -H "Content-Type: application/json" -d '{"uuid": "test1",  "date": "2016-01-01",  "event": "tester data"}' localhost:8080/update_event
#curl -v -X POST -H "Content-Type: application/json" -d '{"uuid": "test1"}' localhost:8080/delete_event
# curl -v -X POST -H "Content-Type: application/json" -d '{"uuid": "test1",  "date": "2017-01-01",  "event": "tester data 1"}' localhost:8080/create_event
POST localhost:8080/create_event
Content-Type: application/json

{
  "uuid": "test1",
  "date": "2022-08-02",
  "event": "tester data 1"
}



###

POST localhost:8080/update_event
Content-Type: application/json

{

}

###

# curl -v -X POST -H "Content-Type: application/json" -d '{"uuid": "test1",  "date": "2016-01-01",  "event": "tester data"}' localhost:8080/update_event
POST localhost:8080/update_event
Content-Type: application/json

{
  "uuid": "test3",
  "date": "2022-08-01",
  "event": "tester data 1"
}

###

POST localhost:8080/update_event
Content-Type: application/json

{
  "uuid": "test1",
  "date": "2017-01-01",
  "event": "tester data"
}

###

# curl -v -X POST -H "Content-Type: application/json" -d '{"uuid": "test1"}' localhost:8080/delete_event
POST localhost:8080/delete_event
Content-Type: application/json

{
  "uuid": "test3",
  "date": "2022-08-01"
}


###

# curl -v -X GET localhost:8080/event_for_day?uuid=test1&date=2018-02-02
GET localhost:8080/event_for_day?uuid=test1&date=2022-01-03

###

GET localhost:8080/event_for_week?uuid=test1&date=2022-01-02

# хедур вынеси ебло!

###
POST localhost:8080/create_event
Content-Type: application/json

{
  "uuid": "test1",
  "date": "2022-01-08",
  "event": "tester data 1"
}

####

#####
POST localhost:8080/create_event
Content-Type: application/json

{
  "uuid": "test1",
  "date": "2022-01-02",
  "event": "tester data 2"
}
#####

GET localhost:8080/event_for_month?uuid=test1&date=2022-01-01

####

